[[artifacts]]
name = "mlcommons_resnet50"
family = "ResNet"
location = "models/mlcommons/models.py"
format = "code"

[artifacts.metadata]
description = "ResNet50 v1.5 model for MLCommons v1.1"

[artifacts.metadata.publication]
url = "https://arxiv.org/abs/1512.03385.pdf"


[[artifacts]]
name = "mlcommons_ssd_mobilenet"
family = "MobileNetV1"
location = "models/mlcommons/models.py"
format = "code"

[artifacts.metadata]
description = "MobileNet v1 model for MLCommons v1.1"

[artifacts.metadata.publication]
url = "https://arxiv.org/abs/1704.04861.pdf"


[[artifacts]]
name = "mlcommons_ssd_resnet34"
family = "ResNet"
location = "models/mlcommons/models.py"
format = "code"

[artifacts.metadata]
description = "ResNet34 model for MLCommons v1.1"

[artifacts.metadata.publication]
url = "https://github.com/mlcommons/inference/tree/master/vision/classification_and_detection"
