[[artifacts]]
name = "mlcommons_resnet50_v1.5_int8"
family = "ResNet"
location = "https://github.com/furiosa-ai/furiosa-models/raw/main/models/mlcommons/mlcommons_resnet50_v1.5_int8.onnx"
format = "onnx"

[artifacts.metadata]
description = "ResNet50 v1.5 model for MLCommons v1.1"

[artifacts.metadata.publication]
url = "https://arxiv.org/abs/1512.03385.pdf"


[[artifacts]]
name = "mlcommons_ssd_mobilenet_v1_int8"
family = "MobileNetV1"
location = "https://github.com/furiosa-ai/furiosa-models/raw/main/models/mlcommons/mlcommons_ssd_mobilenet_v1_int8.onnx"
format = "onnx"

[artifacts.metadata]
description = "MobileNet v1 model for MLCommons v1.1"

[artifacts.metadata.publication]
url = "https://arxiv.org/abs/1704.04861.pdf"


[[artifacts]]
name = "mlcommons_ssd_resnet34_int8"
family = "ResNet"
location = "https://github.com/furiosa-ai/furiosa-models/raw/main/models/mlcommons/mlcommons_ssd_resnet34_int8.onnx"
format = "onnx"

[artifacts.metadata]
description = "ResNet34 model for MLCommons v1.1"

[artifacts.metadata.publication]
url = "https://github.com/mlcommons/inference/tree/master/vision/classification_and_detection"