[package]
name = "furiosa-models"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
# Set name to furiosa to make /python/furiosa/* recognizable
name = "furiosa"
crate-type = ["cdylib"]

# https://maturin.rs/project_layout.html#alternate-python-source-directory-src-layout
[package.metadata.maturin]
python-source = "python"

[dependencies]
pyo3 = { version = "0.16.5", features = ["extension-module"] }
